version: '3.8'

services:
  user_service:
    build: .
    # container_name: user_service
    command: gunicorn src.wsgi:application --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/app
    networks:
      - microservices_shared_network
    # ports:
    #   - "8001:8000"
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres_db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=user_service_db
      - POSTGRES_USER=user_service_user
      - POSTGRES_PASSWORD=a_strong_password
    networks:
      - microservices_shared_network
  
  nginx:
    image: nginx:1.25-alpine
    container_name: user_service_load_balancer
    # ports:
    #   - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservices_shared_network
    depends_on:
      - user_service

networks:
  microservices_shared_network:
    external: true


volumes:
  postgres_data: